export { default as Navbar } from './Navbar/Navbar'
export { default as PartnerCarrousel } from './partners/PartnerCarrousel'
export { default as HeroSection } from './Herosection/HeroSection'
export { default as TitleSection } from './Title/TitleSection'
export { default as CTACards } from './CTACards'
export { default as PhotoGallery } from './Fotogallerij' 